numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/ c 64 insert_0.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/custom/uniform/insert_01/ a 64 insert_01.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/uniform/insert_1/ a 64 insert_1.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/uniform/insert_5/ a 64 insert_5.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/uniform/insert_10/ a 64 insert_10.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/uniform/insert_25/ a 64 insert_25.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/ a 64 insert_50.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/uniform/insert_75/ a 64 insert_75.csv
numactl -N 1 -m 1 ./ycsb /home/eddy/datasets/uniform/uniform/insert_100/ a 64 insert_100.csv
